### ISSUE TITLE
Can I use this with the LBD descriptor?

### ISSUE THREAD

**Issue by apeoej333** [ySalaun/MLSD#5]
I would like to use your MLSD line feature to do visual odometry.

So can I do line matching using MLSD line feature and the LBD descriptor?

Thank you!

**Comment by ySalaun** [comment]
I think the best for this would be to go on my other repository (LineSfM) where there is an opencv conversion of LBD that can be (and is already) plugged into LSD/MLSD or ED-Lines,

Best,

Yohann

**Comment by MathsionYang** [comment]
hi I  want to know how to run it ????
