### ISSUE TITLE
windows issue

### ISSUE THREAD

**Issue by yyfyan** [ySalaun/MLSD#6]
Great job, I use the MLSD in  Windows 10, but I find some bugs and  runtime too long !

**Comment by ySalaun** [comment]
Thank you,
To be honest this code is pretty old and was not really optimized.
On some pictures with too many little segments, the runtime was not acceptable.
This be said, I won't be able to correct the code for you but if you want to push some corrections, feel free !

**Comment by yyfyan** [comment]
Ok.
